name: Qodana PR Lint Check

on:
  pull_request:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Qodana
        uses: JetBrains/qodana-action@v2023.3
        with:
          pr-mode: true
